#!/usr/bin/env node
/**
 * SessionStart Hook — 前回セッションの要約を instructions ファイルに書き出す
 *
 * .github/sessions/ 内の最新セッションファイルを読み、
 * .github/instructions/session-context.instructions.md に書き出す。
 * Copilot は .github/instructions/ を自動読込するため、
 * 前回の文脈が自然にコンテキストに注入される。
 *
 * 公式入力: { timestamp, cwd, source, initialPrompt }
 *
 * 設計原則:
 * - 雛形のままのファイルは書き出さない
 * - セッションがない場合は instructions ファイルを削除（残存コンテキスト防止）
 * - エラー時は exit 0 で非ブロッキング
 */
'use strict';

const fs = require('fs');
const path = require('path');
const {
  SESSION_MAX_AGE_DAYS,
  readFileSafe,
  writeFileSafe,
  getProjectSessionsDir,
  ensureDir,
  findRecentSessions,
  stripAnsi,
  log,
} = require('./lib/session-utils');

const INSTRUCTIONS_DIR = '.github/instructions';
const CONTEXT_FILENAME = 'session-context.instructions.md';

async function main() {
  const cwd = process.cwd();
  const sessionsDir = getProjectSessionsDir(cwd);
  const instructionsDir = path.join(cwd, INSTRUCTIONS_DIR);
  const contextFile = path.join(instructionsDir, CONTEXT_FILENAME);

  ensureDir(sessionsDir);
  ensureDir(instructionsDir);

  const recentSessions = findRecentSessions(sessionsDir, SESSION_MAX_AGE_DAYS);

  if (recentSessions.length === 0) {
    log('No recent sessions found');
    removeContextFile(contextFile);
    return;
  }

  const latest = recentSessions[0];
  log(`Found ${recentSessions.length} recent session(s), latest: ${latest.basename}`);

  const content = stripAnsi(readFileSafe(latest.path) || '');

  if (!content || content.includes('[Session context goes here]')) {
    log('Session file is template-only, skipping injection');
    removeContextFile(contextFile);
    return;
  }

  const instructionsContent = buildInstructionsContent(
    content,
    latest.basename,
    recentSessions
  );
  writeFileSafe(contextFile, instructionsContent);
  log(`Wrote session context to: ${contextFile}`);
}

function buildInstructionsContent(sessionContent, sessionBasename, allSessions) {
  const lines = [
    '---',
    'applyTo: "**"',
    '---',
    '',
    '# Previous Session Context',
    '',
    `> Auto-generated by sessionStart hook. Source: \`${sessionBasename}\``,
    '> This file is git-ignored and regenerated at each session start.',
    '',
    sessionContent,
  ];

  if (allSessions.length > 1) {
    lines.push('', '## Other Recent Sessions', '');
    allSessions.slice(1, 5).forEach((s) => {
      lines.push(`- \`${s.basename}\``);
    });
  }

  return lines.join('\n') + '\n';
}

function removeContextFile(filePath) {
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      log(`Removed stale context file: ${filePath}`);
    }
  } catch (err) {
    log(`Failed to remove context file: ${err.message}`);
  }
}

main().catch((err) => {
  log(`Error: ${err.message}`);
  process.exitCode = 0;
});
